"""Shared provisional beacon-style extraction constants.

These constants preserve current legacy/provisional behavior for regression
comparison. They are not authoritative radar-message semantics.
"""

from __future__ import annotations


DATA_WORD_HEX_WIDTH = 4
CD2_WORD_HEX_WIDTH = 3
WORD_DATA_MASK = 0x0FFF

RANGE_WORD_INDEX = 1
LEGACY_RANGE_WORD_MASK = 0x0FFE
LEGACY_RANGE_WORD_SHIFT = 1
LEGACY_RANGE_NM_SCALE = 0.125
LEGACY_RANGE_NM_DIVISOR = 16.0
BEACON_CANDIDATE_RANGE_NM_SCALE = 0.125

ACP_WORD_INDEX = 2
ACP_DEGREES_PER_CIRCLE = 360.0
ACP_COUNTS_PER_CIRCLE = 4096.0
ACP_DEGREES_PER_COUNT = ACP_DEGREES_PER_CIRCLE / ACP_COUNTS_PER_CIRCLE

MODE_3_WORD_INDEX = 4

ALTITUDE_WORD_INDEX = 6
LEGACY_ALTITUDE_WORD_MASK = 0x07FF
ALTITUDE_WORD_MASK = 0x0FFF
ALTITUDE_VALUE_MASK = 0x07FF
ALTITUDE_SIGN_MASK = 0x0800
ALTITUDE_FEET_PER_COUNT = 100
